services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www
      - ./images/nginx:/etc/nginx/conf.d
      - ./data/logs:/var/log/nginx/
    depends_on:
      - php
      - db
  php:
    build:
      context: ./images/php
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www
      - ./images/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9099:9000"
  db:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - '53099:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8099:80'
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
